### ISSUE TITLE
change intensity

### ISSUE THREAD

**Issue by user34756361233** [rdeangel/esp8266_max7219_rda_msg_board#1]
using your messageboard since a few days and trying to tie it into HA.  Very happy with the result up to now but missing any way to change the intensity of the matrix leds. Is it possible to add that in a new release?

kind regards

Han

**Comment by pepe59** [comment]
I had the same idea see the forum
https://community.home-assistant.io/t/esp8266-max7219-message-board-http-and-mqtt/397654/13
Add brightness control of LED modules from HA similar to text speed and repetition rate.

**Comment by rdeangel** [comment]
I will add this in the new version, it will take at least a couple of weeks for me to get to it though.

**Comment by rdeangel** [comment]
Feature added to [v2022.08.15](https://github.com/rdeangel/esp8266_max7219_rda_msg_board/releases/tag/v2022.08.15).
See change log for other changes.

**Comment by pepe59** [comment]
The LED brightness control works perfectly, thanks.
